pipeline {
    agent {
        label 'Agent - 1'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
     parameters {
        choice(name: 'action', choices: ['Apply', 'Destroy'], description: 'Select one Choise')
    }
    stages {
        stage('Init') {
            steps {
                sh """cd 01-vpc
                ls -la"""
            }
        }
        stage('Test') {
            steps {
                sh 'echo Hello World, from Test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Hello World, from Deploy'
            }
        }
        stage("print params"){
            steps{
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
                echo "triggered test again"
                echo "I am Thor, King of Asgard"
                echo "I am BlackPanther, King of Wakanda"
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
        failure { 
            echo 'I will run when pipeline is failure'
        }

        }
    
    }

