pipeline {
    agent {
        label 'Agent - 1'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
     parameters {
        choice(name: 'action', choices: ['Apply', 'Destroy'], description: 'Select one from the below')
    }
    stages {
        stage('Init') {
            steps {
                sh """
                echo "Current Directory: \$(pwd)"
                echo "Listing contents of the current directory:"
                ls -la
                echo "Changing directory to 01-vpc"
                cd terraform-expense/01-vpc
                echo "Listing contents of 01-vpc:"
                ls -la
            """
                }
            }
        stage('Plan') {
            when{
                expression{
                    params.action == "Apply"
                }
            }
            steps {
                sh 'echo Hello World, from Test'
                }
            }
        stage('Deploy') {
            when{
                expression{
                    params.action == "Destroy"
                }
            }
            steps {
                sh 'echo Hello World, from Deploy'
                }
            }
        }
    }